### ISSUE TITLE
is_mounted is not working in 0.1.2

### ISSUE THREAD

**Issue by Strit** [grinrag/blkinfo#5]
I know this has been fixed in master branch, but there has been no release since this was fixed some 6 months ago, so the pip archive and the AUR does not contain a version with the fix.

Is it possible to get a new release so this can get fixed for the public?

**Comment by grinrag** [comment]
@Strit sorry for the delay in publishing the new version. It's there now. https://pypi.org/project/blkinfo/
I am closing this issue.

**Comment by Strit** [comment]
Thanks. Any change of a regular release tag here in the repo, so the AUR package maintainer will also pick it up? :smiley:
